---
  - name: Inastall Nginx WebServer
    apt: name=nginx state=latest
    notify:
    - restart nginx


  - name: Creates directory
    ansible.builtin.file:
      path: /var/www/html/images
      state: directory


  - name: copying file with playbook
    become: true
    copy:
      src: ./templates/tiger.jpg
      dest: /var/www/html/images/tiger.jpg
      owner: "{{ owner }}"
      group: "{{ group }}"
      mode: "{{ mode }}"


  - name: "{{ name }}"
    file:
      path: "{{ path }}"
      state: "{{ state }}"

  - name: "{{ name }}"
    file:
      path: /etc/nginx/sites-available/default
      state: "{{ state }}"

  - name: copying file with playbook
    become: true
    copy:
      src: "{{ src }}"
      dest: "{{ dest }}"
      owner: "{{ owner }}"
      group: "{{ group }}"
      mode: "{{ mode }}"


  - name: copying file with playbook
    become: true
    copy:
      src: "{{ src }}"
      dest: /etc/nginx/sites-available/image
      owner: "{{ owner }}"
      group: "{{ group }}"
      mode: "{{ mode }}"

  - name: Rename file 
    command: mv /var/www/html/index.nginx-debian.html index1.html


